MySQL:
  Host: 'localhost'
  Database: 'raphaspawners'
  Username: 'root'
  Password: ''

Generator:
  LimitStack: 200
  DistanceStack: 10
  LimitMembers: 21
  SilkTouch: false
  RandomValueSpawn: false
  Delay:
    Init: 4
  WorldBlackList:
    - 'worldexample'
  MobHead:
    Enabled: true
  ItemStack:
    Name: "&eGerador de Monstros"
    Lore:
      - "&7Tipo: &f%spawner_type%"
  Hologram:
    Height: 3
    Lines:
      - "&ex%quantity_generators% Geradores de %spawner_type%"
      - "&eProprietário: &f%owner%"
      - "&eStatus: &f%spawner_status%"

Entities:
  LimitStack: 120
  DistanceStack: 25
  WorldBlackList:
    - 'worldexample'

